### PR TITLE
Update kodi_panel_fb.py

### PR DESCRIPTION
**Pull request by nico1080**
Add direction to avaoid the blinking cursor with the FB method

### CODE REVIEW

**Comment by mattblovell** [comment]
Hi @nico1080,

I saw your initial change, adding the additional instructions to `kodi_panel_fb.py`, and was going to ask whether you were open to making some whitespace and wording changes (or if you minded if I may such changes).  

I'm confused by all the subsequent file changes, though.  Perhaps you wanted to clean up your own installation?  In my experience, it is usually "safer" to make changes that you intend for Pull Requests on a branch.  That way, you can leave your own master branch for your usage.

Since I am unsure about the subsequent file changes, my current thinking is to take your original added documentation and drop it into `kodi_panel_fb.py` manually.  Would that be alright with you?

I'll also separately need to update the `contributors` file.

Thanks,
  Matt

**Comment by nico1080** [comment]
Hi @mattblovell 

You are right, only the first commit was to be commited. The other are just for cleanup in my instalition.
I created a 2nd branch to send you commit (right now it is similar to your master branch), However I don't know how yo send the first commit in this branch.

**Comment by mattblovell** [comment]
> I created a 2nd branch to send you commit (right now it is similar to your master branch), However I don't know how yo send the first commit in this branch.
> 
> Any ideas (It is the first time I tried git hub)

Regarding your question, I think the process would be similar to the Pull Request -- you need a change committed on that branch, for which you can then request a Pull. 

Github's web interface doesn't offer quite as much flexibility as `git` on the command-line, I've found.  I have been looking around to see if I could cherry pick just the first commit that you made on this Pull Request, but I haven't seen a way yet to accomplish that via the web site.  I will search a little bit more but, if I don't find anything, I may close out this request *without* pulling it and make your comment change manually (or I can give you more time to create a separate Pull Request).

  Matt

**Comment by nico1080** [comment]
I think you can close it without pulling, in the same time I will try to send you correct pull request

**Comment by mattblovell** [comment]
Closing per above discussion.  

The original suggestion is still a good one; I'll wait to see a cleaner Pull Request.

**Comment by mattblovell** [comment]
If you check the lastest commit on kodi_panel's master, I think I successfully cherry-picked your addition (with edits) for `kodi_panel_fb.py`.  

Thanks!
  Matt

**Pull request closed without merging**
